### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by rootwork** [exotica-jewelry/multietch-dev#6]
- [ ] [set up redirects](https://github.com/exotica-jewelry/multietch-dev/blob/main/redirects.md)
- [ ] find-replace curly quotes and apostrophes
- [ ] make sure no instances of `multietch-dev` or `exotica-jewelry.github.io/multietch-dev` exist
